# Generated by Django 5.2.17 on 2026-09-18 14:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main headline on banner', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Subheading details', max_length=300)),
                ('badge_text', models.CharField(default='Flash Appliance Sale', max_length=80)),
                ('image_url', models.URLField(default='https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=1200&auto=format&fit=crop&q=80', max_length=500)),
                ('link_url', models.CharField(default='/catalog/', max_length=255)),
                ('button_text', models.CharField(default='Shop Appliance Deals', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'admin_portal_banner',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/')),
                ('origin_country', models.CharField(blank=True, default='Global', max_length=80)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('icon', models.CharField(default='bi-cpu', help_text='Bootstrap icon class name, e.g. bi-snow, bi-fan, bi-tv', max_length=60)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. SUMMER20, WELCOME10', max_length=50, unique=True)),
                ('discount_percent', models.PositiveIntegerField(help_text='Percentage off, e.g. 15 for 15% discount', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('valid_from', models.DateField(default=django.utils.timezone.now)),
                ('valid_until', models.DateField()),
                ('usage_limit', models.PositiveIntegerField(default=100)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'admin_portal_coupon',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='VoltCraft Appliances', max_length=150)),
                ('tagline', models.CharField(default='Smart, Energy-Saving Home Appliances', max_length=255)),
                ('support_email', models.EmailField(default='support@voltcraft.com', max_length=254)),
                ('support_phone', models.CharField(default='1-800-VOLT-HOME', max_length=50)),
                ('currency_symbol', models.CharField(default='₹', max_length=10)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=10000.0, max_digits=10)),
                ('standard_shipping_fee', models.DecimalField(decimal_places=2, default=499.0, max_digits=10)),
                ('order_email_notifications', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'admin_portal_storesetting',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32, unique=True)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='India', max_length=60)),
                ('delivery_instructions', models.TextField(blank=True, help_text='e.g. Elevator access, ground floor, call before arrival')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('coupon_code', models.CharField(blank=True, help_text='Applied coupon code, if any', max_length=50, null=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Order Placed (Pending Processing)'), ('CONFIRMED', 'Order Confirmed & Scheduled for Dispatch'), ('SHIPPED', 'Dispatched / In Transit (Appliance Logistics)'), ('DELIVERED', 'Delivered & Installed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(choices=[('UPI', 'Instant UPI / QR (Google Pay, PhonePe, Paytm, BHIM)'), ('CARD', 'Credit / Debit Card (Visa, MasterCard, RuPay)'), ('NETBANKING', 'Net Banking / Bank Transfer'), ('COD', 'Cash On Delivery / Pay upon Installation')], default='UPI', max_length=20)),
                ('upi_id', models.CharField(blank=True, help_text='e.g. yourname@okhdfcbank or phonepe', max_length=100, null=True)),
                ('card_last_digits', models.CharField(blank=True, help_text='Last 4 digits of card', max_length=4, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('sku', models.CharField(help_text='Stock Keeping Unit / Product Code', max_length=64, unique=True)),
                ('model_number', models.CharField(blank=True, help_text='Manufacturer Model Number', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Original / Regular price in USD', max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, help_text='Discounted sale price', max_digits=10, null=True)),
                ('summary', models.CharField(help_text='Short highlight, e.g. Frost Free Double Door with Twin Inverter', max_length=300)),
                ('description', models.TextField(help_text='Detailed product overview and key selling points')),
                ('energy_rating', models.CharField(choices=[('5-Star', '5-Star Energy Saver'), ('4-Star', '4-Star Inverter'), ('3-Star', '3-Star Standard'), ('2-Star', '2-Star Economy'), ('1-Star', '1-Star Entry'), ('Inverter', 'Smart Dual Inverter'), ('A+++', 'European A+++ Rated'), ('N/A', 'Not Applicable')], default='5-Star', max_length=30)),
                ('capacity', models.CharField(blank=True, help_text='e.g. 450 Litres, 9 kg, 1.5 Ton, 28 Litres', max_length=100)),
                ('warranty', models.CharField(default='1 Year Comprehensive + 10 Years on Motor/Compressor', max_length=150)),
                ('color', models.CharField(blank=True, default='Stainless Steel', max_length=80)),
                ('power_consumption', models.CharField(blank=True, default='230V / 50Hz', max_length=100)),
                ('dimensions', models.CharField(blank=True, help_text='e.g. 70 x 68 x 178 cm', max_length=120)),
                ('stock', models.PositiveIntegerField(default=15)),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_deal_of_the_day', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_url', models.URLField(blank=True, help_text='External image link or CDN fallback', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'db_table': 'orders_orderitem',
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_key', models.CharField(help_text='e.g. Compressor Type, Noise Level, Defrosting Type', max_length=120)),
                ('spec_value', models.CharField(help_text='e.g. Smart Inverter, 38 dB, Frost Free', max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='store.product')),
            ],
            options={
                'verbose_name': 'Product Specification',
                'verbose_name_plural': 'Product Specifications',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('headline', models.CharField(max_length=150)),
                ('comment', models.TextField()),
                ('is_verified_purchase', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('postal_code', models.CharField(blank=True, default='', max_length=10)),
                ('reward_points', models.PositiveIntegerField(default=120)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_userprofile',
            },
        ),
    ]
