# Generated by Django 5.2.17 on 2026-09-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bank_name',
            field=models.CharField(blank=True, help_text='e.g. HDFC Bank, SBI, ICICI', max_length=100, null=True),
        ),
    ]
