# Generated by Django 5.2.17 on 2026-09-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_cancellation_reason_order_cancelled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, help_text='Razorpay Order ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, help_text='Razorpay Payment ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_signature',
            field=models.CharField(blank=True, help_text='Razorpay Payment Signature', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('RAZORPAY', 'Razorpay Gateway (UPI, Cards, NetBanking, QR)'), ('UPI', 'Instant UPI / QR (Google Pay, PhonePe, Paytm, BHIM)'), ('CARD', 'Credit / Debit Card (Visa, MasterCard, RuPay)'), ('NETBANKING', 'Net Banking / Bank Transfer'), ('COD', 'Cash On Delivery / Pay upon Installation')], default='RAZORPAY', max_length=20),
        ),
    ]
