# Generated by Django 5.2.17 on 2026-10-01 06:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_razorpay_order_id_order_razorpay_payment_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('RAZORPAY', 'Razorpay Online (UPI, QR Code, Cards, NetBanking)'), ('COD', 'Cash on Delivery (Pay on Delivery / QR Scan)')], default='RAZORPAY', max_length=20),
        ),
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('order_number', models.CharField(blank=True, help_text='Optional order reference ID', max_length=50)),
                ('feedback_type', models.CharField(choices=[('GENERAL', 'General Store Experience'), ('PRODUCT', 'Product Quality & Variety'), ('DELIVERY', 'Delivery & Installation Service'), ('SUPPORT', 'Customer Service & Support'), ('SUGGESTION', 'Suggestion / Improvement Idea'), ('COMPLAINT', 'Issue / Complaint')], default='GENERAL', max_length=20)),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_approved', models.BooleanField(default=True, help_text='Visible on public feedback page')),
                ('is_featured', models.BooleanField(default=False, help_text='Highlight on testimonials')),
                ('admin_reply', models.TextField(blank=True, help_text='Staff reply to customer feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Feedback',
                'verbose_name_plural': 'Customer Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
